### ISSUE TITLE
New logo/Icon Proposal

### ISSUE THREAD

**Issue by mansya** [AnkitDroidGit/Kotlin-NotePad-Android#1]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by AnkitDroidGit** [comment]
Hi Mansya,
Its pleasure for me. Please proceed with the design.

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you like it ? if yes, which one do you like it ?
![kotlin-notepad-android](https://user-images.githubusercontent.com/33461607/45967397-16625c00-c058-11e8-8c70-1ecc3f83cb6e.png)

Sorry for late respond sir.

**Comment by AnkitDroidGit** [comment]
Thanks for the responding. Icons look great.  Would your please remove android part from the icon. Currently its giving feeling that it product for android. Can you please make it more generic.

**Comment by mansya** [comment]
did you mean like this ? design like it looks generic. I deliberately made a cut like that. so that the logo looks unique.
![kotlin-notepad-android](https://user-images.githubusercontent.com/33461607/46090992-0ffced00-c1dc-11e8-9493-aa70388b1da9.png)

**Comment by AnkitDroidGit** [comment]
I wanted it to be more generic. Thank you Mansya for the great design.
Can you please send me the all resolutions of this icon in all colors. I will try it on app.

**Comment by mansya** [comment]
please tell me what color you choose.

**Comment by mansya** [comment]
I have sent you [**Pull Requests**](https://github.com/AnkitDroidGit/Kotlin-NotePad-Android/pull/2). please check. and I have uploaded all files to the drive.[**Download**](https://drive.google.com/open?id=1gJkd3CkS5Wqg2wWZRxVrP36Mqj7LbTkn)

**Comment by mansya** [comment]
are you not like about this logo ?

**Comment by AnkitDroidGit** [comment]
Sorry. I cancelled it by mistake. Can you please do it again.
